apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment1-deployment
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        envFrom:
          - configMapRef:
              name: assign1-config
          - secretRef:
              name: secret
        ports:
        - containerPort: 80